openapi: 3.0.0
info:
  title: 'Test Api'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: Localhost
  -
    url: 'http://google.com'
    description: google.com
paths:
  /api/v1/auth/signup:
    post:
      tags:
        - Auth
      summary: Signup
      operationId: Signup
      parameters:
        -
          name: email
          in: query
          required: true
          schema:
            type: string
            default: asdsad@qq.ee
        -
          name: name
          in: query
          required: true
          schema:
            type: string
            default: Jimm
        -
          name: password
          in: query
          required: true
          schema:
            type: string
            default: demo1234
      responses:
        201:
          description: 'Success Create user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSignupSuccessResponce'
        404:
          description: 'not found fail'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpNotFoundResponce'
        422:
          description: 'The given data was invalid.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthLoginUnprocessableResponce'
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: login
      parameters:
        -
          name: email
          in: query
          required: true
          schema:
            type: string
            default: asdsad@qq.ee
        -
          name: password
          in: query
          required: true
          schema:
            type: string
            default: demo1234
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthLoginSuccessResponce'
        404:
          description: 'not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpNotFoundResponce'
        422:
          description: 'not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthLoginUnprocessableResponce'
  /api/v1/auth/logout:
    get:
      tags:
        - Auth
      summary: 'LOGS OUT CURRENT LOGGED IN USER SESSION'
      operationId: logout
      responses:
        200:
          description: Success
      security:
        -
          sanctum: []
  /api/v1/auth/user:
    get:
      tags:
        - Auth
      summary: 'LOGS OUT CURRENT LOGGED IN USER SESSION'
      operationId: getAuthenticatedUser
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthUserInfoSuccessResponce'
        404:
          description: 'not found fail'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpNotFoundResponce'
        401:
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpUnauthenticatedResponce'
      security:
        -
          sanctum: []
  /api/v1/label:
    get:
      tags:
        - Label
      summary: 'Get list of Label'
      description: 'Returns list of Label'
      operationId: getLabelList
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelListResponce'
        401:
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpUnauthenticatedResponce'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpForbiddenResponce'
    post:
      tags:
        - Label
      summary: 'Store new Label'
      description: 'Store new Label'
      operationId: storeLabel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreLabelRequest'
      responses:
        201:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelUpdateResponce'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpFailResponce'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpForbiddenResponce'
        422:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelUnprocessableResponce'
  '/api/v1/label/{id}/':
    get:
      tags:
        - Label
      summary: 'Get Label information'
      description: 'Returns Label data'
      operationId: getLabelById
      parameters:
        -
          name: id
          in: path
          description: 'Label id'
          required: true
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelSuccessResponce'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpFailResponce'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpForbiddenResponce'
  /api/v1/test:
    get:
      tags:
        - Tests
      summary: 'Get list of test'
      description: 'Returns list of test'
      operationId: getTestList
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestListResponce'
        401:
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpUnauthenticatedResponce'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpForbiddenResponce'
    post:
      tags:
        - Tests
      summary: 'Store new Test'
      description: 'Store new Test'
      operationId: storeTest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreTestRequest'
      responses:
        201:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestUpdateResponce'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpFailResponce'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpForbiddenResponce'
  '/api/v1/test/{id}/':
    get:
      tags:
        - Tests
      summary: 'Get Test information'
      description: 'Returns Test data'
      operationId: getTestById
      parameters:
        -
          name: id
          in: path
          description: 'Test id'
          required: true
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestSuccessResponce'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpFailResponce'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpForbiddenResponce'
    put:
      tags:
        - Tests
      summary: 'Update Test information'
      description: 'Update Test data'
      operationId: UpdateById
      parameters:
        -
          name: id
          in: path
          description: 'Test id'
          required: true
          schema:
            type: integer
            default: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTestRequest'
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestUpdateResponce'
    delete:
      tags:
        - Tests
      summary: 'Delete Test information'
      description: 'Delete Test data'
      operationId: deleteById
      parameters:
        -
          name: id
          in: path
          description: 'Test id'
          required: true
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: 'Successful operation'
  /:
    get:
      description: 'Home page'
      responses:
        default:
          description: 'Welcome page'
components:
  schemas:
    LoginRequest:
      title: 'Login Request request'
      description: 'Reqest for auth users request body data'
      required:
        - email
        - password
      properties:
        email:
          title: email
          description: 'email for login'
          example: asdsad@qq.ee
        password:
          title: password
          description: 'Username password'
          example: demo1234
      type: object
    SignupRequest:
      title: 'Signup request'
      description: 'Create new account of user'
      required:
        - name
        - email
        - password
      properties:
        name:
          title: name
          description: 'Name of user'
          example: 'Name of user'
        email:
          title: email
          description: 'User email '
          example: qwe@mail.com
        password:
          title: password
          description: 'Username password'
          example: demo1234
      type: object
    StoreLabelRequest:
      title: 'Store Label request'
      description: 'Store Label request body data'
      required:
        - name
        - status
      properties:
        name:
          title: name
          description: 'Name of the new Label'
          example: Green
        status:
          title: status
          description: 'Status Label enabled or no '
          example: 'true'
      type: object
    StoreTestRequest:
      title: 'Store Test request'
      description: 'Store Test request body data'
      required:
        - name
      properties:
        name:
          title: name
          description: 'Name of the new Test'
          example: 'First Test'
      type: object
    UpdateTestRequest:
      title: 'Update Test request'
      description: 'Update Test request body data'
      required:
        - name
      properties:
        name:
          title: name
          description: 'Name of the new Test'
          example: 'First Test'
      type: object
    AuthLoginSuccessResponce:
      title: AuthLoginSuccessResponce
      description: AuthLoginSuccessResponce
      properties:
        user:
          title: user
          description: 'user informations'
          type: array
          items:
            properties:
              id:
                format: int64
                example: '1'
              name:
                format: string
                example: Jimm
              email:
                format: string
                example: asdsad@qq.ee
              email_verified_at:
                format: string
                example: 'null'
              created_at:
                format: string
                example: '2022-03-22T09:35:10.000000Z'
              updated_at:
                format: string
                example: '2022-03-22T09:35:10.000000Z'
            type: object
        access_token:
          title: access_token
          description: access
          format: string
          example: 19|i8o8cUTUqNHawTjzb2LjMXihW0ieyzF2Y9cUosE5
      type: object
    AuthLoginUnprocessableResponce:
      title: AuthLoginUnprocessableResponce
      description: AuthLoginUnprocessableResponce
      properties:
        message:
          title: message
          description: 'message of global error'
          format: string
          example: 'The given data was invalid.'
        errors:
          title: errors
          description: 'message of errors'
          type: array
          items:
            properties:
              email:
                type: array
                items:
                  properties:
                    errors:
                      format: string
                      example: 'The provided credentials are incorrect.'
                  type: object
            type: object
      type: object
    AuthSignupSuccessResponce:
      title: AuthSignupSuccessResponce
      description: AuthSignupSuccessResponce
      properties:
        status:
          title: status
          description: 'Success created user'
          format: string
          example: success
      type: object
    AuthUserInfoSuccessResponce:
      title: AuthUserInfoSuccessResponce
      description: AuthUserInfoSuccessResponce
      properties:
        user:
          title: user
          description: 'user informations'
          type: array
          items:
            properties:
              id:
                format: int64
                example: '1'
              name:
                format: string
                example: Jimm
              email:
                format: string
                example: asdsad@qq.ee
              email_verified_at:
                format: string
                example: 'null'
              created_at:
                format: string
                example: '2022-03-22T09:35:10.000000Z'
              updated_at:
                format: string
                example: '2022-03-22T09:35:10.000000Z'
            type: object
      type: object
    HttpFailResponce:
      title: HttpFailResponce
      description: HttpFailResponce
      properties:
        message:
          title: message
          description: message
          format: string
          example: 'Bad Request'
      type: object
    HttpForbiddenResponce:
      title: HttpForbiddenResponce
      description: HttpForbiddenResponce
      properties:
        message:
          title: message
          description: message
          format: string
          example: Forbidden
      type: object
    HttpNotFoundResponce:
      title: HttpNotFoundResponce
      description: HttpNotFoundResponce
      properties:
        message:
          title: message
          description: message
          format: string
          example: 'Error 404'
      type: object
    HttpSuccessResponce:
      title: HttpSuccessResponce
      description: HttpSuccessResponce
    HttpUnauthenticatedResponce:
      title: HttpUnauthenticatedResponce
      description: HttpUnauthenticatedResponce
      properties:
        message:
          title: message
          description: message
          format: string
          example: Unauthenticated
      type: object
    LabelListResponce:
      title: LabelListResponce
      description: LabelListResponce
      properties:
        labels:
          title: 'Labels[]'
          description: 'array of Labels'
          type: array
          items:
            properties:
              id:
                type: string
                example: '1'
              name:
                type: string
                example: Red
              status:
                type: boolean
                example: 'true'
            type: object
      type: object
    LabelSuccessResponce:
      title: LabelSuccessResponce
      description: LabelSuccessResponce
      properties:
        id:
          title: ID
          description: ID
          format: int64
          example: 1
        name:
          title: name
          description: name
          format: string
          example: 'some name'
        status:
          title: status
          description: status
          format: bool
          example: 'true'
      type: object
    LabelUnprocessableResponce:
      title: HttpUnprocessableResponce
      description: HttpUnprocessableResponce
      properties:
        message:
          title: message
          description: 'message of global error'
          format: string
          example: 'The given data was invalid.'
        errors:
          title: errors
          description: 'message of errors'
          type: array
          items:
            properties:
              email:
                type: array
                items:
                  properties:
                    errors:
                      format: string
                      example: 'The provided credentials are incorrect.'
                  type: object
            type: object
      type: object
    LabelUpdateResponce:
      title: LabelUpdateResponce
      description: LabelUpdateResponce
      properties:
        id:
          title: ID
          description: ID
          format: int64
          example: 1
        name:
          title: name
          description: name
          format: string
          example: 'some name'
        status:
          title: status
          description: 'status of operation '
          format: string
          example: success
      type: object
    TestListResponce:
      title: TestListResponce
      description: TestListResponce
      properties:
        tests:
          title: 'Tests[]'
          description: 'array of Test'
          type: array
          items:
            properties:
              id:
                type: string
                example: '1'
              name:
                type: string
                example: 'qwe qweq qwe qwe'
            type: object
      type: object
    TestSuccessResponce:
      title: TestSuccessResponce
      description: TestSuccessResponce
      properties:
        id:
          title: ID
          description: ID
          format: int64
          example: 1
        name:
          title: name
          description: name
          format: string
          example: 'some name'
      type: object
    TestUpdateResponce:
      title: TestUpdateResponce
      description: TestUpdateResponce
      properties:
        id:
          title: ID
          description: ID
          format: int64
          example: 1
        name:
          title: name
          description: name
          format: string
          example: 'some name'
        status:
          title: status
          description: 'status of operation '
          format: string
          example: success
      type: object
  securitySchemes:
    sanctum:
      type: apiKey
      description: 'Enter token in format (Bearer token)'
      name: Authorization
      in: header
